# fly.toml app configuration file generated for nb-docs on 2023-11-12T08:25:18-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nb-docs"
primary_region = "sea"

[build]
  image = "nb-docs:latest"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]


